services:

  postgres:
    image: postgres:16
    container_name: education_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgres/init:/docker-entrypoint-initdb.d

  redis:
    image: redis:7
    container_name: education_redis
    restart: unless-stopped
    ports:
      - "6379:6379"

  superset:
    build:
      context: ./superset
    container_name: education_superset
    restart: unless-stopped
    depends_on:
      - postgres
      - redis
    ports:
      - "8088:8088"
    environment:
      SUPERSET_SECRET_KEY: ${SUPERSET_SECRET_KEY}
    volumes:
      - superset_home:/app/superset_home

  airflow_db:
    image: postgres:16
    container_name: education_airflow_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    volumes:
      - airflow_db_data:/var/lib/postgresql/data

  
  airflow:
    build:
      context: ./airflow
    container_name: education_airflow
    restart: unless-stopped
    depends_on:
      - airflow_db
      - postgres
    command: webserver
    ports:
      - "8080:8080"
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@airflow_db:5432/airflow
      AIRFLOW__CORE__LOAD_EXAMPLES: "false"

    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./airflow/logs:/opt/airflow/logs
      - ./airflow/plugins:/opt/airflow/plugins
      - ./scripts:/opt/airflow/scripts
      - ./data:/opt/airflow/data
      - ./education_dbt:/opt/airflow/education_dbt
      - ./airflow/dbt:/home/airflow/.dbt
    env_file:
      - ./.env

  airflow_scheduler:
    build:
      context: ./airflow
    container_name: education_airflow_scheduler
    restart: unless-stopped
    depends_on:
      - airflow_db
      - postgres
    command: scheduler
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@airflow_db:5432/airflow
      AIRFLOW__CORE__LOAD_EXAMPLES: "false"


    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./airflow/logs:/opt/airflow/logs
      - ./airflow/plugins:/opt/airflow/plugins
      - ./scripts:/opt/airflow/scripts
      - ./data:/opt/airflow/data
      - ./education_dbt:/opt/airflow/education_dbt
      - ./airflow/dbt:/home/airflow/.dbt

    env_file:
      - ./.env

volumes:
  postgres_data:
  superset_home:
  airflow_db_data: